# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{attach_file_field}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pavlo Galeta", "Igor Galeta"]
  s.date = %q{2011-03-11}
  s.description = %q{Upload files via Swfupload with Freeberry CMS style}
  s.email = %q{superp1987@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/attach_file_field.rb",
    "lib/attach_file_field/form_builder.rb",
    "lib/attach_file_field/middleware.rb",
    "lib/attach_file_field/railtie.rb",
    "lib/attach_file_field/utils.rb",
    "lib/attach_file_field/version.rb",
    "lib/attach_file_field/view_helper.rb",
    "lib/generators/attach_file_field/attach_file_field_generator.rb",
    "lib/generators/attach_file_field/templates/images/cross_ico.gif",
    "lib/generators/attach_file_field/templates/images/select_file.gif",
    "lib/generators/attach_file_field/templates/javascripts/fileprogress.js",
    "lib/generators/attach_file_field/templates/javascripts/handlers.js",
    "lib/generators/attach_file_field/templates/javascripts/swfupload.js",
    "lib/generators/attach_file_field/templates/javascripts/swfupload.queue.js",
    "lib/generators/attach_file_field/templates/swf/expressInstall.swf",
    "lib/generators/attach_file_field/templates/swf/swfupload.swf"
  ]
  s.homepage = %q{http://github.com/galetahub/attach_file_field}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{attach_file_field}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Easy upload files via Swfupload}
  s.test_files = [
    "test/attach_file_field_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

